### PR TITLE
Better Error Surfacing UI w/ highlighted Excel export

### PR DESCRIPTION
**Pull request by dauglyon**
Restructure datatables setup, add excel export, introduce filtering & severity. This is a big change, with lots of datatables-centric workarounds (injecting and filtering out index/header rows, manually manipulating XLSX XML to add highlights). 

Screen Shot 2021-05-21 at 11 41 34 AM

### CODE REVIEW

**Review by Tianhao-Gu — COMMENTED** [review]
I am not a fluent JS person. But overall JS code looks good to me. 
- Seems like `data` was rendered with JS on the front end with no unit test. It might add more difficulties down the road for troubleshooting and testing.
- I am not sure if you have tested a large data set locally. If it loads all data to the front end and processes data there, It might freeze the browser. I've tried to use ajax to resolve this. But again I am not a good JS coder, I could be completely wrong about this. 
https://datatables.net/reference/option/ajax

**Comment by dauglyon** [comment]
@Tianhao-Gu 

I agree that the lack of tests isnt great. I had originally split out the `error_ui.js` file in order to test it, but it turns out adding a JS testing framework to a kbase app is... difficult. I haven;t found an existing example

As for data size, rather than being dom-limited (datatables is paginated) the issue is memory. However, due to this being implemented in a report (a static site) there aren't many good incremental fetching options. That said, how big do we expect these sample files to get? This should handle on the order of thousands of rows, things might get complicated beyond that. I would need examples of edge cases (which I dont think have been generated) to really test this for durability.

**Comment by eapearson** [comment]
My thoughts:

- dependencies should be provided via package.json with pinned versions
- since jQuery is used directly (not just implicitly by DataTables), jQuery should be a direct dependency, otherwise one needs to dig into the data tables source to see the version packaged with it (jQuery is the only dependency in data tables' package.json.)
- it would be awfully nice if the js app didn't use globals; I realize that a relatively small, self-contained app can operate just fine with globally loaded dependencies, and placing things on window. However, a more modular approach (amd would have the lowest browser tech requirements) would be easier to understand and test.

Are there examples of usage in a narrative using this version of the code?

I haven't had time, but would normally want to run the code myself, especially for checking out visuals and behavior in the browser. Is that feasible right now, with the import validation specs in flux and perhaps, in this pr, being different from the sample service?

**Comment by dauglyon** [comment]
@eapearson this is not a js app, just a static site with vanilla JS and no bundling. Hence the lack of any node/npm features like package.json. I can't find any examples of tying in a JS app to a report/kbase app, especially testing would be useful. Do you know of an existing example?

**Comment by dauglyon** [comment]
This version is up as the Dev version on both CI and appdev. Should work with any existing samples test file

**Comment by dauglyon** [comment]
If there is a good way to integrate the JS app to the KBase app deploy flow (which is mostly a mystery to me) it would definitely help with testing, and could be used to manage JS bundling (though, I'm not sure how dependency fetching & building would be integrated with the KBase app side of things)

**Comment by dauglyon** [comment]
Overall, I don't really see the added complexity from using a JS App / node approach adding the the maintainability of the report code, unless testing could be integrated with the kb-sdk test functionality. The big downside there being the lack of npm deps. That said, that seems to be SOP for reports across other apps

**Comment by eapearson** [comment]
Good morning. @dauglyon 

> @eapearson this is not a js app, just a static site with vanilla JS and no bundling. Hence the lack of any node/npm features like package.json. I can't find any examples of tying in a JS app to a report/kbase app, especially testing would be useful. Do you know of an existing example?

We don't hardly if ever have actual front end devs working on reports, so there may not be any examples of good or at least consistent development practices. I haven't looked at the state of html report usage for a long time, other than what comes up in cases like this. However, I think this is an opportunity to set a good precedent :)

I think I get what you mean by not being a standard JS app, but it  quacks like a one, doesn't it?

AMD doesn't require any sort of bundler, in fact it is the OG bundler-less module system!

Node does not need to be involved, other than as a dependency of npm. The point of npm is for deterministic (well, as much as the npm world can be) dependency management, and to document and communicate in one place what those dependencies are.

As far as integration into the KBase sdk workflow, that is a great concern. I think it is one raised by the rising tide of web apps in html reports, not this project as such. 

In this case, the uploader is not a run-of-the-mill sdk app -- it is actually a core part of the sample system. This raises the importance of testing, maintainability, etc. above that of the typical sdk app's html report (imo, imo).

Just for perspective, if you are interested, some recollections (others may recall different):
html reports started primarily as a way to capture and present output created by 3rd party apps that we wrap, and to allow users to directly download program output files. Some of those apps produce entire mini web sites allowing one to explore the program output. As such, these were canned, had no direct connection to kbase services or data. 
We would sometimes need to encase that output in wrappers. E.g. I do recall helping internal users wrap multiple outputs into a simple tabbed interface.
There was always the ability to create report content from scratch though, but that was primarily used for small snippets which were stored directly in the report object rather than in the htmlfileset service.
Anyway, just to say, this was not built with the intention of building our own interfaces and was implemented some time after the sdk was originally built, so developer support, like exists for the service part of sdk apps, was not implemented, if even considered.

**Comment by eapearson** [comment]
That said, I think we should get this in front of people as soon as possible, because it is a big usability win!
That could be done by doing a dev release from the branch itself, if not by merging this and making improvements later.

**Comment by scanon** [comment]
I agree with the last comment.  It is more important to get this in front of users for more feedback.  I don't see a need to add more complexity here.  The JavaScript is here just to make HTML a bit more dynamic.  I don't see this as a full-blown UI app.  It is just table views with some decoration and the java script is helping out here.

If there are any simple tests of the javascript we could add that would make sense, then that would be fine.  But I don't want to burden @dauglyon with developing some entire new methodology from scratch that we don't have an example of for any of the other apps.

**Comment by dauglyon** [comment]
@eapearson I agree that we should try and move relatively quick on this, but it'd be helpful for a review of the JS code itself for any noticeable bugs, if the above wasn't an implicit "LGTM" on that front. 

I have lots of thoughts around the other items which basically boil down to "further architecture design discussion is needed for supporting complex in-house JS reports"

**Comment by dauglyon** [comment]
@scanon I'd say the biggest appeal of a npm/JS app setup is the relative ease/clarity of testing, but I can make a test file with some assertions, and a readme to describe how to run it

**Pull request merged**
